# 01 - YOLO11s BDD100K: fast, small-object-aware training

This is the recommended YOLO notebook for the RTX 3050 Laptop GPU. It replaces
the old CPU-sized YOLO11n schedule with a measured YOLO11s/704 px schedule,
a fixed class- and small-object-aware subset, AMP, realistic road-scene
augmentation, low-learning-rate refinement, held-out model selection, and
calibrated deployment thresholds.

**Preserved baseline from the previous execution**

| split | precision | recall | F1 | mAP50 | mAP50:95 |
|---|---:|---:|---:|---:|---:|
| validation | 0.444 | 0.347 | 0.389 | 0.329 | 0.173 |
| test | 0.466 | 0.349 | 0.399 | 0.338 | 0.179 |

That run used CPU PyTorch, YOLO11n, about 1,400 images, and only 13 epochs.
The table remains here for an honest before/after comparison.

Object detection does not have one classification-style "accuracy." This
notebook reports precision, recall, F1 at IoU 0.50, mAP50, and mAP50:95.
A displayed confidence of 0.80 is a filtering threshold, not 80% accuracy.

## Why this version should improve

Local profiling found that BDD100K traffic lights and signs are overwhelmingly
tiny: 97.7% and 89.5% of their boxes occupy less than 0.25% of the image.
The new manifest therefore rewards rare classes and images containing several
small pedestrians, lights, or signs. YOLO11s has substantially more capacity
than YOLO11n while the measured steady profile remains near two minutes per
1,200-image epoch on this laptop.

The workflow follows transfer-learning and performance recommendations from
[Ultralytics training settings](https://docs.ultralytics.com/modes/train/),
[YOLO11 model scaling](https://docs.ultralytics.com/models/yolo11/), and the
[BDD100K paper](https://arxiv.org/abs/1805.04687). The linked road-segmentation
project reinforces brightness/contrast augmentation and pretrained encoders,
but semantic segmentation is a different output task, so it is not substituted
for box detection here.

In [1]:
from __future__ import annotations

import json
import math
import os
import random
import shutil
import sys
import time
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import yaml
from ultralytics import YOLO

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from road_detection.yolo_training_utils import (
    prepare_fast_data_files,
    stage_fast_data_files,
    stage_images_and_labels,
    uniform_sample,
    write_image_manifest,
)

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("Ultralytics:", __import__("ultralytics").__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

EXPECTED_VENV = Path(r"C:\tf214_hw2\Scripts\python.exe")
if EXPECTED_VENV.exists() and Path(sys.executable).resolve() != EXPECTED_VENV.resolve():
    raise RuntimeError(
        "Select the Jupyter kernel 'Python (tf214_hw2)' and restart the notebook. "
        f"Current interpreter: {sys.executable}"
    )

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.backends.cudnn.benchmark = True
torch.set_float32_matmul_precision("high")

Python: c:\tf214_hw2\Scripts\python.exe
PyTorch: 2.10.0+cu126
Ultralytics: 8.4.112
CUDA available: True
GPU: NVIDIA GeForce RTX 3050 Laptop GPU

In [2]:
# Use "smoke" once after changing code. Use "rtx3050_balanced" for the real run.
RUN_MODE = "rtx3050_balanced"
BASE_RUN_TAG = "yolo11s_704_small_objects_v2"
RESUME_TRAINING = True
RUN_REFINEMENT = True

PROFILES = {
    "smoke": {
        "model": "yolo11s.pt",
        "main_count": 128,
        "refine_count": 128,
        "epoch_val_count": 64,
        "candidate_scan_count": 512,
        "main_epochs": 2,
        "refine_epochs": 1,
        "imgsz": 512,
        "refine_imgsz": 576,
        "batch": 8,
        "refine_batch": 8,
        "patience": 3,
        "final_eval_count": 128,
    },
    "rtx3050_balanced": {
        "model": "yolo11s.pt",
        "main_count": 1200,
        "refine_count": 1200,
        "epoch_val_count": 300,
        "candidate_scan_count": 12000,
        "main_epochs": 60,
        "refine_epochs": 12,
        "imgsz": 704,
        "refine_imgsz": 768,
        "batch": 8,
        "refine_batch": 6,
        "patience": 12,
        "final_eval_count": 1000,
    },
    "overnight_accuracy": {
        "model": "yolo11s.pt",
        "main_count": 1800,
        "refine_count": 1600,
        "epoch_val_count": 400,
        "candidate_scan_count": 16000,
        "main_epochs": 90,
        "refine_epochs": 18,
        "imgsz": 704,
        "refine_imgsz": 768,
        "batch": 8,
        "refine_batch": 6,
        "patience": 18,
        "final_eval_count": 2000,
    },
}
CFG = PROFILES[RUN_MODE]
RUN_TAG = f"{BASE_RUN_TAG}_{RUN_MODE}"

if RUN_MODE != "smoke" and not torch.cuda.is_available():
    raise RuntimeError(
        "The real profiles require CUDA. The prior notebook accidentally used "
        "CPU-only PyTorch; repair/select the tf214_hw2 kernel before training."
    )

DEVICE = 0 if torch.cuda.is_available() else "cpu"
# RAM-cached datasets are fastest with no Windows worker respawn/copy overhead.
WORKERS = 0
DATA_YAML = PROJECT_ROOT / "data" / "bdd100k_yolo" / "data.yaml"
RUN_ROOT = PROJECT_ROOT / "runs" / "notebooks" / "yolo_accuracy"
MANIFEST_DIR = RUN_ROOT / "manifests" / RUN_TAG
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "yolo_final"
FAST_CACHE_BASE = Path(
    os.environ.get("BDD100K_FAST_CACHE")
    or Path(os.environ.get("LOCALAPPDATA", PROJECT_ROOT / "tmp"))
    / "bdd100k_road_detection_cache"
)
LOCAL_CACHE_ROOT = FAST_CACHE_BASE / RUN_TAG
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

if not DATA_YAML.exists():
    raise FileNotFoundError(
        f"Missing {DATA_YAML}. Run scripts/prepare_bdd100k.ps1 with the real "
        "BDD100K folder first."
    )
print(pd.Series(CFG, name=RUN_MODE))

model                   yolo11s.pt
main_count                    1200
refine_count                  1200
epoch_val_count                300
candidate_scan_count         12000
main_epochs                     60
refine_epochs                   12
imgsz                          704
refine_imgsz                   768
batch                            8
refine_batch                     6
patience                        12
final_eval_count              1000
Name: rtx3050_balanced, dtype: object

In [3]:
data_files = prepare_fast_data_files(
    data_yaml=DATA_YAML,
    output_dir=MANIFEST_DIR,
    run_root=RUN_ROOT,
    preferred_manifest_tag=RUN_TAG,
    main_count=CFG["main_count"],
    refine_count=CFG["refine_count"],
    validation_count=CFG["epoch_val_count"],
    seed=SEED,
    candidate_scan_count=CFG["candidate_scan_count"],
    scan_workers=12,
)
staging_started = time.perf_counter()
data_files = stage_fast_data_files(
    data_files,
    cache_root=LOCAL_CACHE_ROOT,
    source_data_yaml=DATA_YAML,
    workers=12,
)
print(f"One-time/reusable local staging: {time.perf_counter() - staging_started:.1f}s")
print("Sampling source:", data_files.source)
print("Main images:", sum(1 for _ in data_files.main_manifest.open()))
print("Refine images:", sum(1 for _ in data_files.refine_manifest.open()))
print("Epoch validation images:", sum(1 for _ in data_files.validation_manifest.open()))
print("Main YAML:", data_files.main_yaml)

One-time/reusable local staging: 6.0s
Sampling source: new small-object-aware candidate index C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\manifests\yolo11s_704_small_objects_v2_rtx3050_balanced\candidate_index.jsonl (12000 scenes); staged in local cache C:\Users\vipra\AppData\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced
Main images: 1200
Refine images: 1200
Epoch validation images: 300
Main YAML: C:\Users\vipra\AppData\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\manifests\main.yaml

## Main transfer-learning stage

The main stage trains one continuous optimizer schedule. This avoids the
previous notebook's short frozen/unfrozen restarts, which reset momentum and
produced a worse second stage. Moderate mosaic, scale, color, and horizontal
flip augmentation cover BDD100K lighting and weather without destroying tiny
traffic-light geometry. The final ten epochs automatically close mosaic.

A one-time parallel staging cell first hydrates the selected files into a local non-OneDrive cache. The first CUDA epoch then includes only kernel and RAM-cache warm-up. Compare steady epochs,
not the first one. On the measured laptop, 1,200 training and 300 validation
images at 704 px are budgeted for roughly 90-120 seconds per steady epoch.

In [4]:
MAIN_NAME = f"{RUN_TAG}_main"
MAIN_DIR = RUN_ROOT / MAIN_NAME
MAIN_LAST = MAIN_DIR / "weights" / "last.pt"

if RESUME_TRAINING and MAIN_LAST.exists():
    print("Resuming:", MAIN_LAST)
    main_model = YOLO(str(MAIN_LAST))
    main_model.train(resume=True)
else:
    main_model = YOLO(CFG["model"])
    main_model.train(
        data=str(data_files.main_yaml),
        epochs=CFG["main_epochs"],
        imgsz=CFG["imgsz"],
        batch=CFG["batch"],
        device=DEVICE,
        workers=WORKERS,
        cache="ram" if torch.cuda.is_available() else False,
        amp=torch.cuda.is_available(),
        optimizer="AdamW",
        lr0=0.002,
        lrf=0.05,
        cos_lr=True,
        warmup_epochs=2.0,
        weight_decay=0.0005,
        box=7.5,
        cls=0.70,
        dfl=1.5,
        hsv_h=0.015,
        hsv_s=0.55,
        hsv_v=0.35,
        degrees=2.0,
        translate=0.08,
        scale=0.35,
        shear=0.0,
        perspective=0.0002,
        fliplr=0.5,
        flipud=0.0,
        mosaic=0.65,
        mixup=0.05,
        close_mosaic=min(10, CFG["main_epochs"]),
        # Fixed shapes avoid repeated cuDNN autotuning on this 4 GB GPU.
        patience=CFG["patience"],
        max_det=300,
        plots=True,
        deterministic=False,
        seed=SEED,
        project=str(RUN_ROOT),
        name=MAIN_NAME,
        exist_ok=True,
        verbose=True,
    )

MAIN_BEST = MAIN_DIR / "weights" / "best.pt"
if not MAIN_BEST.exists():
    raise FileNotFoundError(f"Training did not create {MAIN_BEST}")
print("Main candidate:", MAIN_BEST)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11s.pt to 'yolo11s.pt': 100% ━━━━━━━━━━━━ 18.4MB 4.7MB/s 3.9s3.9s<0.0sss0
New https://pypi.org/project/ultralytics/8.4.113 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.112  Python-3.11.9 torch-2.10.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=ram, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.7, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=C:\Users\vipra\AppData\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\manifests\main.yaml, degrees=2.0, deterministic=False, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=60, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.55, hsv_v=0.35, imgsz=704, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.002, lrf=0.05, mask_ratio=4, max_det=300, mixup=0.05, mode=train, model=yolo11s.pt, momentum=0.937, mosaic=0.65, multi_scale=0.0, name=yolo11s_704_small_objects_v2_rtx3050_balanced_main, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=12, perspective=0.0002, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_main, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.35, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.08, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=2.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    821730  ultralytics.nn.modules.head.Detect           [6, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,430,114 parameters, 9,430,098 gradients, 21.6 GFLOPs

Remapped 4/6 cls head rows from pretrained weights by class name
Transferred 499/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
WARNING train: Slow image access detected (ping: 0.10.0 ms, read: 4.31.7 MB/s, size: 70.7 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\train... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 208.4it/s 5.8s0.0s
train: New cache created: C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\train.cache
train: Caching images (0.9GB RAM): 100% ━━━━━━━━━━━━ 1200/1200 1.2Kit/s 1.0s0.1s
WARNING val: Slow image access detected (ping: 0.10.0 ms, read: 2.41.5 MB/s, size: 52.3 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\val... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 268.8it/s 1.1s0.0s
val: New cache created: C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\val.cache
val: Caching images (0.2GB RAM): 100% ━━━━━━━━━━━━ 300/300 1.2Kit/s 0.2s<0.1s
optimizer: AdamW(lr=0.002, momentum=0.937) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_main\labels.jpg...
Image sizes 704 train, 704 val
Using 0 dataloader workers
Logging results to C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_main
Starting training for 60 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/60      2.68G      1.759      2.054      1.171        325        704: 100% ━━━━━━━━━━━━ 150/150 1.9s/it 4:501.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.5s/it 29.0s0.6s
                   all        300       5459       0.36      0.262       0.22     0.0992

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/60      2.65G      1.759      1.894      1.176        185        704: 100% ━━━━━━━━━━━━ 150/150 1.4s/it 3:301.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.2s0.6s
                   all        300       5459       0.39      0.277      0.255      0.118

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/60      2.67G      1.732       1.81      1.172        209        704: 100% ━━━━━━━━━━━━ 150/150 1.4s/it 3:341.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.4it/s 13.8s0.7s
                   all        300       5459      0.384       0.32      0.268       0.13

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/60      2.62G      1.713      1.778      1.155        247        704: 100% ━━━━━━━━━━━━ 150/150 1.8s/it 4:241.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.4s0.6s
                   all        300       5459      0.425      0.334      0.295      0.138

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/60      2.63G      1.702      1.735      1.149        309        704: 100% ━━━━━━━━━━━━ 150/150 1.5s/it 3:451.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.1it/s 17.6s1.0s
                   all        300       5459      0.369      0.342      0.303      0.139

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/60      2.65G      1.671      1.702      1.135        145        704: 100% ━━━━━━━━━━━━ 150/150 1.7s/it 4:211.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.6it/s 11.8s0.7s
                   all        300       5459      0.413      0.359      0.306      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/60      2.65G      1.656      1.656       1.12        233        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:221.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.3s0.6s
                   all        300       5459      0.388      0.363      0.302       0.14

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/60      2.63G      1.646      1.632      1.114        243        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:171.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.452      0.382      0.336      0.162

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/60      2.64G      1.624      1.585      1.104        220        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:171.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s0.6s
                   all        300       5459      0.416      0.364      0.323       0.15

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/60      2.62G      1.628      1.583      1.107        243        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.394      0.415      0.346      0.164

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/60      2.65G      1.602       1.55      1.092        205        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.475      0.373      0.353      0.171

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/60       2.6G      1.601      1.527      1.088        210        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.456      0.375      0.352      0.168

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/60      2.66G      1.558      1.478      1.079        272        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 10.9s0.6s
                   all        300       5459      0.459      0.419      0.377      0.185

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/60      2.65G      1.578      1.484      1.079        169        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:171.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.2s0.6s
                   all        300       5459      0.493       0.39       0.37      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/60      2.64G      1.548      1.474      1.073        206        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 10.9s0.6s
                   all        300       5459      0.482      0.408      0.381      0.186

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/60      2.71G      1.553      1.464      1.071        260        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:181.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s0.6s
                   all        300       5459      0.531      0.414      0.415      0.204

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/60      2.68G      1.545      1.446       1.07        222        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:181.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s0.6s
                   all        300       5459      0.454      0.418      0.381      0.187

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/60      2.66G      1.531      1.425      1.059        282        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.465      0.426      0.391      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/60      2.63G      1.521      1.399      1.056        176        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:151.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s0.6s
                   all        300       5459      0.579      0.398      0.416      0.211

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/60      2.64G       1.51      1.388      1.052        145        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:151.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s0.6s
                   all        300       5459      0.556      0.403      0.398      0.201

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/60      2.65G      1.509      1.379      1.051        203        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s0.6s
                   all        300       5459      0.519      0.436      0.428      0.216

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/60      2.63G       1.51      1.366      1.054        211        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.559      0.434      0.441      0.226

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/60      2.62G      1.487      1.341      1.048        211        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.554      0.423      0.443      0.224

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/60      2.67G      1.483      1.337      1.041        228        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.531      0.435      0.426      0.215

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/60      2.65G      1.467       1.31      1.037        237        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:151.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.8it/s 10.8s0.6s
                   all        300       5459      0.541       0.41      0.426      0.219

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/60       2.6G      1.467      1.307      1.039        229        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:171.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 10.9s0.6s
                   all        300       5459      0.508      0.443      0.442      0.225

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/60      2.64G      1.471      1.309      1.041        170        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s0.6s
                   all        300       5459      0.547      0.426      0.441      0.225

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/60      2.63G      1.457      1.296      1.034        344        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:161.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.555      0.422      0.441      0.224

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/60      2.62G      1.437      1.267      1.029        279        704: 100% ━━━━━━━━━━━━ 150/150 1.3s/it 3:151.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s0.6s
                   all        300       5459      0.565      0.422      0.435      0.222

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

## Small-object refinement

Refinement starts from the main best checkpoint, uses the stronger
small-object-biased manifest, increases resolution to 768 px, lowers the
learning rate, and mostly disables mosaic. It is deliberately short.
The next section evaluates both checkpoints on the exact same images and
rejects refinement if it regresses.

In [5]:
REFINE_NAME = f"{RUN_TAG}_refine"
REFINE_DIR = RUN_ROOT / REFINE_NAME
REFINE_LAST = REFINE_DIR / "weights" / "last.pt"
REFINE_BEST = REFINE_DIR / "weights" / "best.pt"

if RUN_REFINEMENT:
    if RESUME_TRAINING and REFINE_LAST.exists():
        print("Resuming:", REFINE_LAST)
        refine_model = YOLO(str(REFINE_LAST))
        refine_model.train(resume=True)
    else:
        refine_model = YOLO(str(MAIN_BEST))
        refine_model.train(
            data=str(data_files.refine_yaml),
            epochs=CFG["refine_epochs"],
            imgsz=CFG["refine_imgsz"],
            batch=CFG["refine_batch"],
            device=DEVICE,
            workers=WORKERS,
            cache="ram" if torch.cuda.is_available() else False,
            amp=torch.cuda.is_available(),
            optimizer="AdamW",
            lr0=0.00045,
            lrf=0.10,
            cos_lr=True,
            warmup_epochs=1.0,
            weight_decay=0.0005,
            box=8.0,
            cls=0.80,
            dfl=1.5,
            hsv_h=0.012,
            hsv_s=0.40,
            hsv_v=0.28,
            degrees=1.0,
            translate=0.05,
            scale=0.20,
            fliplr=0.5,
            mosaic=0.20,
            mixup=0.0,
            close_mosaic=min(5, CFG["refine_epochs"]),
            patience=max(4, CFG["refine_epochs"] // 2),
            max_det=300,
            plots=True,
            deterministic=False,
            seed=SEED + 1,
            project=str(RUN_ROOT),
            name=REFINE_NAME,
            exist_ok=True,
            verbose=True,
        )
    if not REFINE_BEST.exists():
        raise FileNotFoundError(f"Refinement did not create {REFINE_BEST}")

New https://pypi.org/project/ultralytics/8.4.113 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.112  Python-3.11.9 torch-2.10.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=6, bgr=0.0, box=8.0, cache=ram, cfg=None, channels_last=False, classes=None, close_mosaic=5, cls=0.8, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=C:\Users\vipra\AppData\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\manifests\refine.yaml, degrees=1.0, deterministic=False, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=12, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.012, hsv_s=0.4, hsv_v=0.28, imgsz=768, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.00045, lrf=0.1, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_main\weights\best.pt, momentum=0.937, mosaic=0.2, multi_scale=0.0, name=yolo11s_704_small_objects_v2_rtx3050_balanced_refine, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=6, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_refine, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.2, seed=43, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.05, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=1.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    821730  ultralytics.nn.modules.head.Detect           [6, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,430,114 parameters, 9,430,098 gradients, 21.6 GFLOPs

Transferred 499/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
WARNING train: Slow image access detected (ping: 1.00.3 ms, read: 4.60.8 MB/s, size: 65.7 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\train... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 105.5it/s 11.4s0.2s
train: New cache created: C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\train.cache
train: Caching images (1.1GB RAM): 100% ━━━━━━━━━━━━ 1200/1200 351.2it/s 3.4s0.0s
WARNING val: Slow image access detected (ping: 2.91.1 ms, read: 15.93.5 MB/s, size: 60.4 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\val.cache... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300  0.0s
val: Caching images (0.3GB RAM): 100% ━━━━━━━━━━━━ 300/300 333.6it/s 0.9s0.0s
optimizer: AdamW(lr=0.00045, momentum=0.937) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.000515625), 87 bias(decay=0.0)
Plotting labels to C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_refine\labels.jpg...
Image sizes 768 train, 768 val
Using 0 dataloader workers
Logging results to C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_refine
Starting training for 12 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/12      2.46G      1.587      1.582       1.05        184        768: 100% ━━━━━━━━━━━━ 200/200 1.4s/it 4:491.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.2it/s 20.0s0.5s
                   all        300       5459      0.581      0.469      0.491      0.261

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/12      2.44G      1.533      1.483      1.031        117        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:361.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.6s0.5s
                   all        300       5459      0.604      0.466        0.5      0.268

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/12      2.47G       1.52      1.452      1.024        114        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:401.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.1s0.5s
                   all        300       5459      0.566       0.49      0.514      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/12      2.46G      1.503      1.407      1.021        168        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:451.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.7it/s 14.7s0.6s
                   all        300       5459      0.583      0.484      0.508      0.273

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/12      2.46G      1.492      1.393      1.013        162        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:481.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.6s0.5s
                   all        300       5459      0.615      0.462      0.512      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/12      2.46G       1.47       1.36      1.006        155        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:381.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.6s0.5s
                   all        300       5459      0.591      0.498      0.513      0.273

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/12      2.45G      1.475      1.346      1.005        129        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:371.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.6s0.5s
                   all        300       5459      0.627      0.478      0.518      0.282
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/12      2.43G       1.46      1.306     0.9959        116        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:351.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.6s0.5s
                   all        300       5459      0.616      0.484      0.523      0.282

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/12      2.45G      1.452      1.296     0.9911        134        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:351.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.7s0.5s
                   all        300       5459      0.606      0.493       0.52      0.281

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/12      2.45G      1.442      1.283     0.9897         91        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:351.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.5s0.5s
                   all        300       5459      0.632      0.486      0.525      0.284

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/12      2.44G      1.432      1.265     0.9873        124        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:351.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.5s0.5s
                   all        300       5459      0.626      0.499       0.53      0.287

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/12      2.46G      1.437      1.263     0.9831         92        768: 100% ━━━━━━━━━━━━ 200/200 1.1s/it 3:351.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.7s0.5s
                   all        300       5459      0.634      0.493       0.53      0.287

12 epochs completed in 0.796 hours.
Optimizer stripped from C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_refine\weights\last.pt, 19.2MB
Optimizer stripped from C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_refine\weights\best.pt, 19.2MB

Validating C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_refine\weights\best.pt...
Ultralytics 8.4.112  Python-3.11.9 torch-2.10.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 101 layers, 9,415,122 parameters, 0 gradients, 21.3 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.6s0.5s
                   all        300       5459      0.637      0.491      0.528      0.286
                   car        297       3074      0.786      0.648      0.722      0.428
                   bus         35         45      0.433      0.475      0.438      0.325
                 truck         84        129      0.581      0.434      0.465      0.296
            pedestrian         99        392      0.691      0.415      0.491      0.234
         traffic light        163        785      0.655      0.476        0.5      0.165
          traffic sign        254       1034      0.677      0.498      0.553       0.27
Speed: 1.1ms preprocess, 27.2ms inference, 0.0ms loss, 2.2ms postprocess per image
Results saved to C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_refine

## No-regression model selection

Candidates are compared on one untouched fixed validation manifest. Selection
emphasizes mAP50 while still rewarding F1 and localization quality. The older
executed YOLO11n checkpoint is included when it exists, so the new run must
actually beat it rather than merely finish training.

In [6]:
def summarize_yolo(metrics):
    precision = float(metrics.box.mp)
    recall = float(metrics.box.mr)
    f1 = 2 * precision * recall / max(1e-12, precision + recall)
    map50 = float(metrics.box.map50)
    map50_95 = float(metrics.box.map)
    quality = 0.55 * map50 + 0.30 * f1 + 0.15 * map50_95
    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "map50": map50,
        "map50_95": map50_95,
        "quality": quality,
    }

candidates = {"main": MAIN_BEST}
if RUN_REFINEMENT and REFINE_BEST.exists():
    candidates["refine"] = REFINE_BEST
OLD_BASELINE = (
    PROJECT_ROOT / "runs" / "notebooks" / "yolo"
    / "bdd100k_cpu_quick_finetuned" / "weights" / "best.pt"
)
if OLD_BASELINE.exists():
    candidates["old_cpu_baseline"] = OLD_BASELINE

candidate_rows = []
candidate_metrics = {}
for name, weights in candidates.items():
    print(f"Evaluating {name}: {weights}")
    metrics = YOLO(str(weights)).val(
        data=str(data_files.main_yaml),
        imgsz=CFG["refine_imgsz"],
        batch=CFG["refine_batch"],
        device=DEVICE,
        workers=WORKERS,
        conf=0.001,
        iou=0.70,
        max_det=300,
        plots=False,
        verbose=False,
    )
    row = {"candidate": name, "weights": str(weights), **summarize_yolo(metrics)}
    candidate_rows.append(row)
    candidate_metrics[name] = metrics

candidate_table = pd.DataFrame(candidate_rows).sort_values("quality", ascending=False)
display(candidate_table)
winner_name = str(candidate_table.iloc[0]["candidate"])
winner_path = Path(candidate_table.iloc[0]["weights"])
winner_metrics = candidate_metrics[winner_name]
FINAL_WEIGHTS = OUTPUT_DIR / "bdd100k_yolo11s_best.pt"
shutil.copy2(winner_path, FINAL_WEIGHTS)
candidate_table.to_csv(OUTPUT_DIR / "candidate_comparison.csv", index=False)
print("Selected:", winner_name)
print("Deployment weights:", FINAL_WEIGHTS)

Evaluating main: C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_main\weights\best.pt
Ultralytics 8.4.112  Python-3.11.9 torch-2.10.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 101 layers, 9,415,122 parameters, 0 gradients, 21.3 GFLOPs
val: Fast image access  (ping: 0.50.5 ms, read: 51.126.9 MB/s, size: 43.1 KB)
val: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\val.cache... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 50/50 2.0it/s 25.1s0.4ss
                   all        300       5459      0.596      0.466      0.491      0.259
Speed: 1.7ms preprocess, 64.9ms inference, 0.0ms loss, 2.7ms postprocess per image
Evaluating refine: C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo_accuracy\yolo11s_704_small_objects_v2_rtx3050_balanced_refine\weights\best.pt
Ultralytics 8.4.112  Python-3.11.9 torch-2.10.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 101 layers, 9,415,122 parameters, 0 gradients, 21.3 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 215.758.0 MB/s, size: 44.3 KB)
val: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\val.cache... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 50/50 2.5it/s 20.4s0.4ss
                   all        300       5459      0.637      0.492       0.53      0.287
Speed: 1.8ms preprocess, 49.6ms inference, 0.0ms loss, 2.9ms postprocess per image
Evaluating old_cpu_baseline: C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\runs\notebooks\yolo\bdd100k_cpu_quick_finetuned\weights\best.pt
Ultralytics 8.4.112  Python-3.11.9 torch-2.10.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11n summary (fused): 101 layers, 2,583,322 parameters, 0 gradients, 6.3 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 272.968.9 MB/s, size: 60.2 KB)
val: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\val.cache... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 50/50 3.3it/s 15.3s0.3s
                   all        300       5459      0.453      0.365      0.348      0.173
Speed: 1.8ms preprocess, 30.3ms inference, 0.0ms loss, 3.8ms postprocess per image

,candidate,weights,precision,recall,f1,map50,map50_95,quality
1,refine,C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-...,0.637364,0.491648,0.555102,0.529919,0.287465,0.501106
0,main,C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-...,0.596145,0.465948,0.523066,0.490765,0.258749,0.465653
2,old_cpu_baseline,C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-...,0.453477,0.365136,0.404540,0.347658,0.173040,0.338530

Selected: refine
Deployment weights: C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\outputs\yolo_final\bdd100k_yolo11s_best.pt

In [7]:
# Build reproducible, bounded final validation and test manifests.
base_config = yaml.safe_load(DATA_YAML.read_text(encoding="utf-8"))
dataset_root = Path(base_config["path"])
if not dataset_root.is_absolute():
    dataset_root = (DATA_YAML.parent / dataset_root).resolve()

def split_dir(split_name):
    value = Path(base_config[split_name])
    return value if value.is_absolute() else dataset_root / value

final_val_images = uniform_sample(
    sorted(split_dir("val").glob("*.jpg")),
    CFG["final_eval_count"],
    SEED + 20,
)
final_test_dir = split_dir("test") if "test" in base_config else None
if final_test_dir is None or not final_test_dir.exists():
    raise FileNotFoundError("Converted data.yaml must contain the held-out local test split.")
final_test_images = uniform_sample(
    sorted(final_test_dir.glob("*.jpg")),
    CFG["final_eval_count"],
    SEED + 21,
)
final_val_images = stage_images_and_labels(
    final_val_images, LOCAL_CACHE_ROOT, "val", workers=12
)
final_test_images = stage_images_and_labels(
    final_test_images, LOCAL_CACHE_ROOT, "test", workers=12
)
final_val_manifest = write_image_manifest(MANIFEST_DIR / "final_val.txt", final_val_images)
final_test_manifest = write_image_manifest(MANIFEST_DIR / "final_test.txt", final_test_images)

final_config = dict(base_config)
final_config["path"] = dataset_root.as_posix()
final_config["val"] = final_val_manifest.resolve().as_posix()
final_config["test"] = final_test_manifest.resolve().as_posix()
FINAL_DATA_YAML = MANIFEST_DIR / "final_eval.yaml"
FINAL_DATA_YAML.write_text(yaml.safe_dump(final_config, sort_keys=False), encoding="utf-8")

final_model = YOLO(str(FINAL_WEIGHTS))
final_val_metrics = final_model.val(
    data=str(FINAL_DATA_YAML),
    split="val",
    imgsz=CFG["refine_imgsz"],
    batch=CFG["refine_batch"],
    device=DEVICE,
    workers=WORKERS,
    conf=0.001,
    iou=0.70,
    max_det=300,
    plots=True,
    verbose=False,
)
final_test_metrics = final_model.val(
    data=str(FINAL_DATA_YAML),
    split="test",
    imgsz=CFG["refine_imgsz"],
    batch=CFG["refine_batch"],
    device=DEVICE,
    workers=WORKERS,
    conf=0.001,
    iou=0.70,
    max_det=300,
    plots=False,
    verbose=False,
)
final_table = pd.DataFrame(
    [
        {"split": "validation", **summarize_yolo(final_val_metrics)},
        {"split": "test", **summarize_yolo(final_test_metrics)},
    ]
)
display(final_table)
final_table.to_csv(OUTPUT_DIR / "final_metrics.csv", index=False)

Ultralytics 8.4.112  Python-3.11.9 torch-2.10.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 101 layers, 9,415,122 parameters, 0 gradients, 21.3 GFLOPs
WARNING val: Slow image access detected (ping: 0.20.0 ms, read: 23.351.1 MB/s, size: 52.1 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\val... 1000 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1000/1000 104.4it/s 9.6s0s
val: New cache created: C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\val.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 167/167 2.2it/s 1:170.4sss
                   all       1000      18077      0.609      0.503      0.526      0.286
Speed: 1.8ms preprocess, 53.0ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\notebooks\runs\detect\val-4
Ultralytics 8.4.112  Python-3.11.9 torch-2.10.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
WARNING val: Slow image access detected (ping: 0.20.1 ms, read: 2.71.3 MB/s, size: 60.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\test... 1000 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1000/1000 228.8it/s 4.4s1s
val: New cache created: C:\Users\vipra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\bdd100k_road_detection_cache\yolo11s_704_small_objects_v2_rtx3050_balanced\labels\test.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 167/167 2.5it/s 1:080.4sss
                   all       1000      18919      0.638      0.492      0.528      0.286
Speed: 1.7ms preprocess, 49.7ms inference, 0.0ms loss, 2.8ms postprocess per image

        split  precision    recall        f1     map50  map50_95   quality
0  validation   0.609124  0.503185  0.551110  0.526426  0.285755  0.497730
1        test   0.637587  0.492183  0.555528  0.528199  0.285568  0.500003

## Calibrate balanced and high-precision live thresholds

The balanced profile chooses each class's best validation F1. The
high-precision profile chooses the lowest threshold that reaches at least
80% precision when the validation curve supports it, with a hard displayed
confidence floor of 0.70. This can produce 0.70-0.80 confidence labels while
remaining honest about the resulting recall.

In [8]:
def calibrate_thresholds(metrics, target_precision=0.80, confidence_floor=0.70):
    box = metrics.box
    px = np.asarray(box.px)
    p_curve = np.asarray(box.p_curve)
    r_curve = np.asarray(box.r_curve)
    f1_curve = np.asarray(box.f1_curve)
    names = metrics.names
    balanced = {}
    high_precision = {}
    rows = []
    for class_id in range(len(names)):
        best_f1_index = int(np.nanargmax(f1_curve[class_id]))
        balanced_threshold = float(px[best_f1_index])
        valid = np.flatnonzero(
            (p_curve[class_id] >= target_precision)
            & (px >= confidence_floor)
        )
        if len(valid):
            strict_index = int(valid[np.nanargmax(r_curve[class_id, valid])])
        else:
            strict_index = int(np.argmin(np.abs(px - confidence_floor)))
        strict_threshold = max(confidence_floor, float(px[strict_index]))
        balanced[str(class_id)] = round(max(0.05, balanced_threshold), 3)
        high_precision[str(class_id)] = round(strict_threshold, 3)
        rows.append(
            {
                "class_id": class_id,
                "class": names[class_id],
                "balanced_threshold": balanced[str(class_id)],
                "balanced_f1": float(f1_curve[class_id, best_f1_index]),
                "strict_threshold": high_precision[str(class_id)],
                "strict_precision": float(p_curve[class_id, strict_index]),
                "strict_recall": float(r_curve[class_id, strict_index]),
                "target_precision_met": bool(p_curve[class_id, strict_index] >= target_precision),
            }
        )
    return balanced, high_precision, pd.DataFrame(rows)

balanced_thresholds, strict_thresholds, threshold_table = calibrate_thresholds(
    final_val_metrics
)
display(threshold_table)
threshold_table.to_csv(OUTPUT_DIR / "threshold_calibration.csv", index=False)

deployment_config = {
    "backend": "yolo",
    "weights": FINAL_WEIGHTS.name,
    "imgsz": CFG["refine_imgsz"],
    "max_det": 300,
    "default_threshold_profile": "balanced",
    "threshold_profiles": {
        "balanced": {
            "inference_confidence": 0.05,
            "class_thresholds": balanced_thresholds,
            "meaning": "Per-class validation F1 optimum",
        },
        "high_precision_80": {
            "inference_confidence": 0.70,
            "class_thresholds": strict_thresholds,
            "target_validation_precision": 0.80,
            "meaning": "At least 0.70 displayed confidence; class target is 0.80 precision where supported",
        },
    },
    "selection": winner_name,
    "validation_metrics": summarize_yolo(final_val_metrics),
    "test_metrics": summarize_yolo(final_test_metrics),
}
DEPLOYMENT_CONFIG = OUTPUT_DIR / "deployment_config.json"
DEPLOYMENT_CONFIG.write_text(json.dumps(deployment_config, indent=2), encoding="utf-8")
print("Deployment config:", DEPLOYMENT_CONFIG)

,class_id,class,balanced_threshold,balanced_f1,strict_threshold,strict_precision,strict_recall,target_precision_met
0,0,car,0.315,0.712642,0.701,0.981132,0.348340,True
1,1,bus,0.301,0.460716,0.867,0.802567,0.171975,True
2,2,truck,0.233,0.464976,0.701,0.806288,0.199052,True
3,3,pedestrian,0.240,0.522619,0.701,0.969944,0.092403,True
4,4,traffic light,0.301,0.570394,0.701,0.979071,0.017994,True
5,5,traffic sign,0.278,0.581096,0.701,0.916039,0.162841,True

Deployment config: C:\Users\vipra\OneDrive\Documents\GitHub\ECGR-5106-Intro-To-Deep-Learning\Final_Project\outputs\yolo_final\deployment_config.json

In [9]:
# Reload after validation so the predictor owns ordinary, mutable tensors.
benchmark_model = YOLO(str(FINAL_WEIGHTS))
# Warm GPU, measure end-to-end detector throughput, and show representative output.
benchmark_images = [str(path) for path in final_val_images[:100]]
_ = benchmark_model.predict(
    benchmark_images[:8],
    imgsz=CFG["refine_imgsz"],
    batch=CFG["refine_batch"],
    device=DEVICE,
    quantize=16 if torch.cuda.is_available() else None,
    conf=0.25,
    verbose=False,
)
if torch.cuda.is_available():
    torch.cuda.synchronize()
started = time.perf_counter()
benchmark_results = benchmark_model.predict(
    benchmark_images,
    imgsz=CFG["refine_imgsz"],
    batch=CFG["refine_batch"],
    device=DEVICE,
    quantize=16 if torch.cuda.is_available() else None,
    conf=0.25,
    verbose=False,
)
if torch.cuda.is_available():
    torch.cuda.synchronize()
elapsed = time.perf_counter() - started
print(f"End-to-end throughput: {len(benchmark_images) / elapsed:.2f} images/s")
print(f"Latency: {1000 * elapsed / len(benchmark_images):.1f} ms/image")

figure, axes = plt.subplots(2, 2, figsize=(16, 9))
for axis, result in zip(axes.flat, benchmark_results[:4]):
    axis.imshow(result.plot()[..., ::-1])
    axis.axis("off")
plt.tight_layout()
plt.show()

End-to-end throughput: 1.99 images/s
Latency: 503.1 ms/image

## Realtime command

```powershell
python -m road_detection.realtime_detect `
  --backend yolo `
  --weights outputs\yolo_final\bdd100k_yolo11s_best.pt `
  --config outputs\yolo_final\deployment_config.json `
  --threshold-profile high_precision_80 `
  --source 0 `
  --device 0
```

Use `balanced` for the best precision/recall tradeoff. Use
`high_precision_80` when cleaner, 0.70+ confidence labels matter more than
recall. Keep the candidate comparison and final tables with the project
report; they show whether the requested target was measured rather than
assumed.